

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=file:myapp.db?cache=shared&_foreign_keys=1
    volumes:
      - .:/app
